/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String _kFontPkg = null;

  static const IconData address = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_arrow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sos = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData telephone = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData work = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}